export const STANDARD_SETS = [
  'CORE', 'EXPERT1',
  'DALARAN', 'ULDUM', 'WILD_EVENT', 'DRAGONS',
  'YEAR_OF_THE_DRAGON', 'BLACK_TEMPLE', 'DEMON_HUNTER_INITIATE'
];

export const CLASS_HEROS = {
  'MAGE': [637],
  'HUNTER': [31],
  'PRIEST': [813],
  'WARLOCK': [893],
  'ROGUE': [930],
  'DRUID': [274],
  'SHAMAN': [1066],
  'WARRIOR': [7],
  'PALADIN': [671],
  'DEMONHUNTER': [56550],
};
